config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :tasks, only: [:new, :create]
  	member do
  		get :done
  		get :undone
  	end
  end

  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	has_many :tasks, -> { order "id asc" }, inverse_of: :list, dependent: :destroy
	accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
	belongs_to :user

	validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: /\w+@\D+\.{1}[a-zA-Z]{2,}/ }
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  def default_url_options
    { host: "https://benstodolist.herokuapp.com/" || "localhost:3000" }
  end
  
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @lists = policy_scope(List)
  end

  def show
  end

  def new
    @list = List.new
    authorize @list
    @task = Task.new
  end

  def create
    @list = List.new(list_params)
    @list.title.capitalize!
    authorize @list
    @list.user = current_user
    @tasks = []
    @allTasks = params[:list][:tasks_attributes].values
    @allTasks.each do |task|
      @tasks << Task.new(description: task[:description].capitalize, list: @list)
    end
    @list.tasks = @tasks
    if @list.save!
      redirect_to list_path(@list), notice: "#{@list.title} was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    @tasks = params[:list][:tasks_attributes].values
    @tasks.each do |task|
      task[:description].capitalize!
    end
    if @list.update(list_params)
      redirect_to list_path(@list), notice: "#{@list.title} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def done
    @task = Task.find(params[:id]) # find the correct task
    @list = List.find(@task.list_id) # find which list this task is connected to
    @task.status = true
    @task.save
    authorize @list
    respond_to do |format|
      format.html { redirect_to list_path(@list) if @task.save! }
      format.js
    end
  end

  def undone
    @task = Task.find(params[:id])
    @list = List.find(@task.list_id)
    @task.status = false
    @task.save
    authorize @list
    respond_to do |format|
      format.html { redirect_to list_path(@list) if @task.save! }
      format.js
    end
  end

  private

  def list_params
    params.require(:list).permit(:title, tasks_attributes: [:id, :description, :_destroy])
  end

  def set_list
    @list = List.find(params[:id])
    authorize @list
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_list, only: [:new, :create]

  def new
  	@task = Task.new
  end

  private

  def set_list
    @list = List.find(params[:list_id])
    authorize @list
  end

  def task_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/lists/_done.html.erb
<%= link_to done_list_path(task), :task => task.id, remote: true do %>
	<i class="far fa-check-circle checkmark"></i>	
<% end %>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :title,
              input_html: { class: "input-style" },
              placeholder: "Groceries" %>
  <h3> <strong> Tasks </strong> </h3>
  <div id='tasks'>
    <%= f.simple_fields_for :tasks do |task| %>
      <%= render 'task_fields', :f => task %>
    <% end %>
    <div class='links mt-4 link-underline-add'>
      <%= link_to_add_association 'Add a new task', f, :tasks %>
    </div>
  </div>
  <%= f.submit 'Save', class: "my-2 btn-blue btn-block font-weight-bold" %>
<% end %>

app/views/lists/_list_index.html.erb
<% lists.each_with_index do |list, index| %>
	<p data-list-id= "<%= list.id %>"> 
		<span class="highlight">
			<%= "#{index+1}. " %>
			<%= link_to list_path(list) do  %>
				<%= list.title %>
			<% end %>
			<% if policy(list).destroy? %>
				<%= link_to list_path(list), method: :delete, remote: true do %>
					<i class="far fa-trash-alt"></i>
				<% end %>
			<% end %>
		</span>
	</p>
<% end %>

app/views/lists/_show.html.erb
<span data-task-id= "<%= task.id %>">
	<% if task.status? %>
		<h5> 
			<span class="highlight">
				[<i class="fas fa-check checkmark"></i>] <del> <%= task.description %> </del>
				<% if policy(@list).undone? %>
					<%= render 'undone', task: task %>
				<% end %>
			</span>
		</h5>
	<% else %>
		<h5> 
			<span class="highlight">
				[ ] <%= task.description %>
				<% if policy(@list).done? %>
					<%= render 'done', task: task %>
				<% end %>
			</span>
		</h5>
	<% end %>
</span>

app/views/lists/_task_fields.html.erb
<div class='nested-fields'>
    <%= f.input :description,
    						input_html: { class: "input-style" },
    						placeholder: "Buy 4 apples" %>
    <%= link_to_remove_association f, class: "link-underline" do %>
			Remove this task <i class="fas fa-hand-point-up"></i>
    <% end %>
</div>

app/views/lists/_undone.html.erb
<%= link_to undone_list_path(task), :task => task.id, remote: true do %>
	<i class="fas fa-undo-alt undo"></i>
<% end %>

app/views/lists/destroy.js.erb
document.querySelector("[data-list-id='<%= @list.id %>']").remove();

app/views/lists/done.js.erb
function taskDone() {
	let done = document.querySelector("[data-task-id='<%= @task.id %>']");
	done.innerHTML = '<%= j render "show", task: @task %>'
}

taskDone();

app/views/lists/index.html.erb
<div class="container-margins">
		<div class="headers-box">
			<h1> My To Do Lists </h1>
		</div>

		<% if !user_signed_in? %>
			<p> Looks like you're not signed in. </p>
			<p class="last-line"> Once you sign in you can start creating lists. </p>
			<%= link_to "Sign in", new_user_session_path, class: "btn-blue" %>
		<% elsif @lists.empty? %>
			<p> You don't have any to do lists. </p>
			<p> If there is something you need to do you can create a new list </p>
		<% else %>
			<%= render 'list_index', lists: @lists  %>
		<% end %>		

	<% if user_signed_in? %>
		<% if policy(List).create? %>
			<div class="btn-margin">
				<%= link_to "Add a list", new_list_path(@list), class: "btn-blue mb-2" %>
			</div>
		<% end %>
	<% end %>

</div>

app/views/lists/new.html.erb
<div class="container-margins">
	<div class="btn-back-margin">
		<%= link_to lists_path, class: "btn-back" do %>
			<i class="fas fa-chevron-circle-left"></i> Your lists
		<% end %>
	</div>

	<div class="headers-box">
		<h1> New list </h1>
	</div>

	<%= render "form" %>
</div>

app/views/lists/show.html.erb
<div class="container-margins">
	<div class="btn-back-margin">
    <%= link_to lists_path, class: "btn-back" do %>
      <i class="fas fa-chevron-circle-left"></i> Your lists
    <% end %>
  </div>

	<% if policy(@list).show? %>
		<div class="headers-box">
			<h1> <%= @list.title %> </h1>
		</div>

		<% @list.tasks.each do |task| %>
			<%= render 'show', task: task %>
		<% end %>

		<% if policy(@list).edit? %>
			<%= link_to "Add/edit/delete tasks", new_list_task_path(@list), class: "btn-add" %>
		<% end %>
	<% end %>
</div>

app/views/lists/undone.js.erb
function taskUnDone() {
	let undone = document.querySelector("[data-task-id='<%= @task.id %>']");
	undone.innerHTML = '<%= j render "show", task: @task %>'
}

taskUnDone();

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer font-small special-color-dark footer-links footer-background">
  <div class="container mt-2">
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
				<%= link_to "https://github.com/benattali", class: "footer-link", target: :_blank do  %>
					<i class="fab fa-github"></i>
				<% end %>
      </li>
      <li class="list-inline-item">
				<%= link_to "https://www.linkedin.com/in/ben-attali", class: "mx-5 footer-link", target: :_blank do  %>
					<i class="fab fa-linkedin"></i>
				<% end %>
      </li>
      <li class="list-inline-item">
				<%= link_to "https://www.instagram.com/benattali/", class: "footer-link", target: :_blank do  %>
					<i class="fab fa-instagram"></i>
				<% end %>
      </li>
    </ul>
  </div>

  <div class="footer-copyright text-center mb-2">
  	© Ben Attali • 
  	2019 •
    <%= link_to "benattali.com", "https://benattali.com", target: :_blank %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-user navbar-link">
  <%= link_to "All lists", root_path, class: "navbar-brand nav-lists-border"%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if !user_signed_in? %>
          <%= link_to  "Sign in", new_user_session_path, class: "nav-link nav-signup-border" %>
        <% else %>
          <li class="nav-item">
            <div class="nav-email align-bottom">
              <%= current_user.email %>
            </div>
          </li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link nav-signup-border" %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/tasks/_task_fields.html.erb
<div class='nested-fields mt-4'>
    <%= f.input :description,
    						input_html: { class: "input-style" } %>
    <%= link_to_remove_association f, class: "link-underline" do %>
			Remove this task <i class="fas fa-hand-point-up"></i>
    <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container-margins">
	<div class="btn-back-margin">
    <%= link_to list_path(@list), class: "btn-back" do %>
      <i class="fas fa-chevron-circle-left"></i> <%= @list.title %>
    <% end %>
  </div>

	<%= simple_form_for @list do |f| %>
		<div id='tasks'>
	    <%= f.simple_fields_for :tasks do |task| %>
	      <%= render 'task_fields', :f => task %>
	    <% end %>
	   	<div class='links mt-4 link-underline-add'>
	   		<%= link_to_add_association 'Add a new task', f, :tasks %>
	   	</div>
	  </div>
	  <%= f.submit 'Save', class: "my-2 btn-blue btn-block font-weight-bold" %>
	<% end %>
</div>